### ISSUE TITLE
Add Molivar Logo And Signature In Assets

### ISSUE THREAD

**Issue by MarcoDoC** [Molivair/dinos#21]
**Is your feature request related to a problem? Please describe.**
/

**Describe the solution you'd like**
Add Molivair logo and signature assets into assets/image that will be used on candidate and pure assets and wherever needed.

**Describe alternatives you've considered**
/

**Additional context**
/

**Comment by airscripts** [comment]
Good idea.  
We should place those assets into https://github.com/molivair/canvas too, in order to have them every time we create a new collection.

**Comment by airscripts** [comment]
I've added the issue: https://github.com/molivair/canvas/issues/2.
